<a href="https://colab.research.google.com/github/sirjoecabz/Pytorch-Tutorial-Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.







In [4]:
import torch
import numpy as np

# **LISTS**


In [2]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.40307028, 0.0829594 , 0.30881284, 0.80070114],
       [0.19499369, 0.15752986, 0.78835019, 0.74923848],
       [0.11372841, 0.34575476, 0.77067389, 0.55474641]])

In [6]:
np1.dtype


dtype('float64')

# **TENSORS**

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.3590, -0.7511,  0.0412,  0.4551],
        [ 1.0968, -0.4117, -0.1846, -0.2482],
        [-2.8044, -1.6538,  0.9534,  1.3533]])

In [9]:
tensor_2d.dtype

torch.float32

In [10]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-0.6836,  0.3054, -1.9861,  0.3260],
         [-0.5857, -0.9370,  0.3218, -1.3215],
         [-0.2791,  0.5781,  1.5911, -1.6476]],

        [[-1.3334, -0.4799, -0.0716,  0.5661],
         [-0.0927, -0.5124,  1.0659, -0.4842],
         [ 0.2138,  0.0042,  0.9764,  0.4409]]])

In [12]:
tensor_4d = torch.ones(2,3,4)
tensor_4d

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4031, 0.0830, 0.3088, 0.8007],
        [0.1950, 0.1575, 0.7884, 0.7492],
        [0.1137, 0.3458, 0.7707, 0.5547]], dtype=torch.float64)